x-airflow-common:
  &airflow-common    
  build:
      context: ./airflow # Certifique-se que o Dockerfile está aqui
  env_file:
    - .env    
  # Pulls the image name from the .env file
  image: ${AIRFLOW_IMAGE_NAME}

  user: ${AIRFLOW_UID} # Default of Airflow # Importante para permissões de escrita em Linux
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    - ${PROJECT_ROOT}/pipelines:/opt/pipelines
    - ${PROJECT_ROOT}/volumes/airflow/logs:/opt/airflow/logs 
    - ${PROJECT_ROOT}/volumes/airflow/plugins:/opt/airflow/plugins  
    - ${PROJECT_ROOT}/secrets/kaggle.json:/home/airflow/.config/kaggle/kaggle.json
  environment:
    &airflow-common-env    
    AIRFLOW_UID: ${AIRFLOW_UID}
    AIRFLOW__CELERY__WORKER_CONCURRENCY: 2
    AIRFLOW__SCHEDULER__PARSING_PROCESSES: 2
    AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
    AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
    AIRFLOW__CORE__DAGS_FOLDER: /opt/pipelines/dags  
    PYTHONPATH: /opt/pipelines  
    AIRFLOW__CORE__EXECUTOR: LocalExecutor       
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_USER}
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'   
    MINIO_ENDPOINT: http://minio:9000 
  networks:          
    - airflow-network   
  

services:
  postgres:
    image: postgres:15.10-alpine    
    ports:
      - "5433:5432"
    networks:          
      - airflow-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}  
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  
    env_file:
      - .env
    volumes:                                      
      - ${PROJECT_ROOT}/volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5     

  redis:
    image: redis:7-alpine
    networks:         
      - airflow-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common    
    user: "0:0"    
    # 'db migrate' is much safer and more reliable than 'version' for initialization
    command: >      
      bash -c "chown -R 50000:0 /opt/airflow/logs /opt/airflow/dags /opt/airflow/plugins && airflow db migrate"
    # command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD}      
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }

  airflow-scheduler:
    <<: *airflow-common    
    command: scheduler
    restart: always
    depends_on:
      airflow-init: { condition: service_completed_successfully }     

  airflow-webserver:    
    <<: *airflow-common
    command: webserver
    restart: always
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      airflow-init: { condition: service_completed_successfully }

  minio:   
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1    
    container_name: minio_server
    networks:
      - airflow-network
    env_file:    
    - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ${PROJECT_ROOT}/lakehouse:/data 
    command: server /data --console-address ":9001"       
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5  

  spark-master:
    build: ./spark
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    user: root # Switch to administrator mode.
    environment:
      - SPARK_MODE=master
    env_file:
      - .env
    ports:
      - "7077:7077"
      - "8081:8080"
    networks:
      - airflow-network
    volumes:
      - ${PROJECT_ROOT}/pipelines/scripts:/opt/spark/jobs

  spark-worker:
    build: ./spark
    container_name: spark-worker
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    user: root # Switch to administrator mode.
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    env_file:
      - .env
    networks:
      - airflow-network  
    volumes:
      - ${PROJECT_ROOT}/pipelines/scripts:/opt/spark/jobs 

  dremio:
    image: dremio/dremio-oss:26.0    
    user: root      
    container_name: dremio
    ports:
    - "9047:9047"
    - "31010:31010"
    - "45678:45678"
    networks:
    - airflow-network
    volumes:
    - ${PROJECT_ROOT}/volumes/dremio:/opt/dremio/data   
    #command: chown -R 1000:1000 /opt/dremio/data 
    restart: always

  jupyter:
    build: ./jupyter
    ports:
    - "8888:8888"
    networks:
    - airflow-network
    volumes:
    - ${PROJECT_ROOT}/notebooks:/home/jovyan/work
    environment:
    - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    - JUPYTER_ENABLE_LAB=yes   

networks:
  airflow-network:
    driver: bridge
